version: "3.8"

services:
  mysql-leave:
    image: mysql:latest
    restart: unless-stopped
    environment:
       MYSQL_DATABASE: 'lms-leave'
       MYSQL_USER: 'admin'
       MYSQL_PASSWORD: 'password'
       MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3316:3306 
    healthcheck:
      test: "exit 0"
  leave-service:
    depends_on:
        mysql-leave:
            condition: service_healthy
    build: .
    ports:
      - 8102:8102
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysql-leave:3306/lms-leave?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true",
        "spring.datasource.username" : "admin",
        "spring.datasource.password" : "password",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "none",
        "spring.flyway.url":"jdbc:mysql://mysql-leave:3306/lms-leave?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true",
        "spring.flyway.user":"root",
        "spring.flyway.password":"password"
      }'
    volumes:
    - .m2:/root/.m2
    stdin_open: true
    tty: true