version: "3.8"

services:
  lms_db:
    image: mysql:latest
    #restart: unless-stopped
    environment:
       MYSQL_DATABASE: 'lms_user'
       MYSQL_USER: 'admin'
       MYSQL_PASSWORD: 'password'
       MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3306:3306 
    healthcheck:
      test: "exit 0"
  user-service:
    depends_on:
        lms_db:
            condition: service_healthy
    #build: .
    image: arjunkshenoy/lms-user-service:latest
    ports:
      - 8081:8081
    expose:
      - "8081"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://lms_db:3306/lms_user?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true",
        "spring.datasource.username" : "admin",
        "spring.datasource.password" : "password",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "none",
        "spring.flyway.url":"jdbc:mysql://lms_db:3306/lms_user?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true",
        "spring.flyway.user":"admin",
        "spring.flyway.password":"password"
      }'
#  mysql_leave_db:
#    image: mysql:latest
#    #restart: unless-stopped
#    environment:
#       MYSQL_DATABASE: 'lms_leave'
#       MYSQL_USER: 'admin'
#       MYSQL_PASSWORD: 'password'
#       MYSQL_ROOT_PASSWORD: 'password'
#    ports:
#      - 3316:3316 
#    healthcheck:
#      test: "exit 0"
  leave-service:
    depends_on:
        lms_db:
            condition: service_healthy
    #build: C:\Users\arjun\Documents\SE\SEM1\Software_Design\Project\repo\lms .
    image: arjunkshenoy/lms-leave-service:latest
    ports:
      - 8102:8102
    expose:
      - "8102"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://lms_db:3306/lms_user?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true",
        "spring.datasource.username" : "admin",
        "spring.datasource.password" : "password",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "none",
        "spring.flyway.url":"jdbc:mysql://lms_db:3306/lms_user?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true",
        "spring.flyway.user":"admin",
        "spring.flyway.password":"password"
      }'
